version: '3.8'

services:
  pmbot-api:
    build: .
    container_name: pm-bot-api
    ports:
      - "5000:5000"    # Uncomment for EC2 Nginx to connect to your container
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DEBUG=${DEBUG}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRES=${JWT_ACCESS_TOKEN_EXPIRES}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DEFAULT_LLM_PROVIDER=${DEFAULT_LLM_PROVIDER}
      - AZURE_DEVOPS_PAT=${AZURE_DEVOPS_PAT}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
      - JIRA_SERVER_URL=${JIRA_SERVER_URL}
      - JIRA_EMAIL=${JIRA_EMAIL}
      - JIRA_PROJECT_KEY=${JIRA_PROJECT_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPO_NAME=${GITHUB_REPO_NAME}
      - GITHUB_REPO_OWNER=${GITHUB_REPO_OWNER}
      - GITHUB_BASE_URL=${GITHUB_BASE_URL}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - TEAMS_WEBHOOK_URL=${TEAMS_WEBHOOK_URL}
      - COST_TRACKING_ENABLED=${COST_TRACKING_ENABLED}
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    networks:
      - pmbot-network

  db:
    image: mysql:8.0
    container_name: pm-bot-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pmbot_db
      MYSQL_USER: pmbot
      MYSQL_PASSWORD: pmbot123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pmbot-network

volumes:
  mysql_data:

networks:
  pmbot-network:
    driver: bridge
