"""Add teams_user_id to User model

Revision ID: 4d3ff899f64e
Revises: 
Create Date: 2025-07-16 21:40:28.237497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3ff899f64e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teams_user_id', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint(None, ['teams_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('teams_user_id')

    # ### end Alembic commands ###
