name: Build and deploy Python app to Azure Web App - pm-bot-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Verify application files
        run: |
          echo "=== Application Files Check ==="
          ls -la
          
          echo "=== Verifying required files ==="
          for file in wsgi.py app.py requirements.txt config.py; do
            if [ -f "$file" ]; then
              echo "✓ $file found"
            else
              echo "✗ $file missing"
              exit 1
            fi
          done
          
          echo "=== Flask app folder check ==="
          if [ -d "app" ]; then
            echo "✓ app/ folder found"
            ls -la app/
          else
            echo "✗ app/ folder missing"
            exit 1
          fi
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Test basic imports (optional)
        run: |
          echo "Testing basic Python syntax..."
          python -c "
          try:
              import wsgi
              print('✓ wsgi.py syntax is valid')
          except Exception as e:
              print(f'⚠ wsgi.py import issue: {e}')
          
          try:
              from config import config
              print('✓ config.py imports successfully')
          except Exception as e:
              print(f'⚠ config.py import issue: {e}')
          "
        continue-on-error: true
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CA47F2A525364A2EBACCC6660D3F856E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_86330DC39FE64A1A8D44A6A55F30E5A4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2194892073364D0D929143F931B93D00 }}
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pm-bot-app'
          package: .
