name: Build and deploy Python app to Azure Web App - pm-bot-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Check repository structure
        run: |
          echo "=== Repository root contents ==="
          ls -la
          echo "=== Looking for pm-bot-api folder ==="
          find . -name "requirements.txt" -type f
          echo "=== Full directory structure ==="
          find . -type d -name "pm-bot-api"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Find the correct path to requirements.txt
          if [ -f "pm-bot-api/requirements.txt" ]; then
            echo "Installing from pm-bot-api/requirements.txt"
            pip install -r pm-bot-api/requirements.txt
          elif [ -f "requirements.txt" ]; then
            echo "Installing from requirements.txt"
            pip install -r requirements.txt
          else
            echo "ERROR: requirements.txt not found"
            exit 1
          fi
      
      - name: Verify files exist
        run: |
          echo "=== Repository structure ==="
          ls -la
          
          echo "=== Looking for application files ==="
          find . -name "wsgi.py" -type f
          find . -name "requirements.txt" -type f
          
          # Check if files exist in expected location
          if [ -f "pm-bot-api/wsgi.py" ]; then
            echo "✓ pm-bot-api/wsgi.py found"
          elif [ -f "wsgi.py" ]; then
            echo "✓ wsgi.py found in root"
          else
            echo "✗ wsgi.py not found"
            exit 1
          fi
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CA47F2A525364A2EBACCC6660D3F856E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_86330DC39FE64A1A8D44A6A55F30E5A4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2194892073364D0D929143F931B93D00 }}
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pm-bot-app'
          package: pm-bot-api
