name: Build and deploy Python app to Azure Web App - pm-bot-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Verify required files
        run: |
          echo "=== Checking for required files ==="
          for file in wsgi.py app.py requirements.txt config.py; do
            if [ -f "$file" ]; then
              echo "✓ $file found"
            else
              echo "✗ $file missing"
              exit 1
            fi
          done

          echo "=== Checking app/ folder ==="
          if [ -d "app" ]; then
            echo "✓ app/ folder found"
            ls -la app/
          else
            echo "✗ app/ folder missing"
            exit 1
          fi

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate Python syntax
        run: |
          echo "Checking Python syntax..."
          python -m py_compile wsgi.py
          python -m py_compile app.py
          python -m py_compile config.py
          echo "✓ Syntax check passed"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CA47F2A525364A2EBACCC6660D3F856E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_86330DC39FE64A1A8D44A6A55F30E5A4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2194892073364D0D929143F931B93D00 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pm-bot-app'
          package: .
          startup-command: gunicorn wsgi:app --bind=0.0.0.0:$PORT --timeout 600      

      - name: Print DB init instructions
        run: |
          echo ""
          echo "⚠ Database initialization NOT run in GitHub Actions."
          echo "To initialize your DB after deploy:"
          echo ""
          echo "1. Go to Azure Portal → Your Web App → SSH Console"
          echo "2. Run these commands:"
          echo ""
          echo "   cd /home/site/wwwroot"
          echo "   python init_db.py"
          echo ""
          echo "✅ Done! Your DB will be initialized with sample data."
