name: Build and deploy Python app to Azure Web App - pm-bot-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CA47F2A525364A2EBACCC6660D3F856E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_86330DC39FE64A1A8D44A6A55F30E5A4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2194892073364D0D929143F931B93D00 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pm-bot-app'
          package: .
          startup-command: gunicorn wsgi:app --bind=0.0.0.0:$PORT --timeout 600

      - name: Initialize database
        run: |
          python init_db.py

      - name: Verify deployment
        run: |
          echo "=== Verifying deployment ==="
          for i in {1..5}; do
            echo "Attempt $i: Testing app response..."
            if curl -f -s "https://pm-bot-app-amaycnbqgfgmhqgb.eastasia-01.azurewebsites.net/" >/dev/null 2>&1; then
              echo "✓ App is responding"
              break
            elif [ $i -eq 5 ]; then
              echo "✗ App is not responding after several attempts"
              exit 1
            else
              echo "App not ready yet. Waiting 30 seconds..."
              sleep 30
            fi
          done
          echo "Deployment verification completed."
